### ISSUE TITLE
Trace spacing less than 0.1mm

### ISSUE THREAD

**Issue by KINEX605** [kr239/Macintosh-Classic-Reloaded#3]
Hello,

I wanted to have this PCB produced by PCBway using the MacintoshClassicGerbers-v1.2d-FINAL.zip file, but their audit returned an issue with at least one trace having less than 0.1mm spacing.

![0918163440316t](https://github.com/kr239/Macintosh-Classic-Reloaded/assets/33550854/a4819770-4e20-4a41-a3c7-80b59e6dfb0e)

**Comment by kr239** [comment]
Can you zoom out - that looks like a PLCC pad, but i'm unable to see where that issue is.

**Comment by KINEX605** [comment]
That is all of the information that PCBWay provided. Based on my inspection of the design in the viewer, I believe the trace in question is for one of the M5M44256BJ chips.

![Mac_Classic_Trace_Zoom_Out](https://github.com/kr239/Macintosh-Classic-Reloaded/assets/33550854/c560bb05-d196-473b-addd-f4df95991f17)

**Comment by kr239** [comment]
Great - thanks for that - I've just made some trace adjustments - new gerbers inbound! :)
